# ============================================================================
# Generated by httpxgen. DO NOT EDIT.
# ============================================================================


from collections.abc import Mapping
from typing import Self
from uuid import UUID

import httpx
from pydantic import TypeAdapter

from preview.invoices.models import (
    CreateInvoiceRequest,
    Invoice,
    InvoicePage,
    InvoiceStatus,
    ListInvoicesParams,
)
from preview.shared import ApiError, apply_security, serialize_path, serialize_query
from preview.shared.models import ApiErrorModel


class InvoicesClient:
    def __init__(
        self,
        client: httpx.AsyncClient,
        base_url: str,
        *,
        headers: Mapping[str, str] | None = None,
        credentials: Mapping[str, str | tuple[str, str]] | None = None,
        timeout: float = 30.0,
    ) -> None:
        self._client = client
        self._base_url = base_url.rstrip("/")
        self._headers = dict(headers) if headers else {}
        self._credentials = dict(credentials) if credentials else {}
        self._timeout = timeout

    async def aclose(self) -> None:
        await self._client.aclose()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.aclose()

    async def list_invoices(
        self,
        status: InvoiceStatus | None = None,
        cursor: str | None = None,
        page_size: int = 25,
        *,
        timeout: float | None = None,
    ) -> InvoicePage:
        path = "/invoices"

        params = ListInvoicesParams(
            status=status,
            cursor=cursor,
            page_size=page_size,
        )
        query: list[tuple[str, str]] = []
        if params.status is not None:
            query.extend(serialize_query("status", params.status))
        if params.cursor is not None:
            query.extend(serialize_query("cursor", params.cursor))
        query.extend(serialize_query("page_size", params.page_size))

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, query, {})

        response = await self._client.request(
            method="GET",
            url=f"{self._base_url}{path}",
            params=query,
            headers=headers,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            return InvoicePage.model_validate(response.json())

        raise ApiError(response.status_code, response.text, response=response)

    async def create_invoice(
        self,
        body: CreateInvoiceRequest,
        *,
        timeout: float | None = None,
    ) -> Invoice:
        path = "/invoices"

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        json_body = TypeAdapter(CreateInvoiceRequest).dump_python(
            body, mode="json", by_alias=True, exclude_none=True
        )

        response = await self._client.request(
            method="POST",
            url=f"{self._base_url}{path}",
            headers=headers,
            json=json_body,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 201:
            return Invoice.model_validate(response.json())
        if response.status_code == 422:
            parsed_body = ApiErrorModel.model_validate(response.json())
            raise ApiError(response.status_code, response.text, parsed_body, response)

        raise ApiError(response.status_code, response.text, response=response)

    async def get_invoice(
        self,
        invoice_id: UUID,
        *,
        timeout: float | None = None,
    ) -> Invoice:
        path = "/invoices/{invoiceId}"
        path = path.replace("{invoiceId}", serialize_path("invoiceId", invoice_id))

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        response = await self._client.request(
            method="GET",
            url=f"{self._base_url}{path}",
            headers=headers,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            return Invoice.model_validate(response.json())
        if response.status_code == 404:
            parsed_body = ApiErrorModel.model_validate(response.json())
            raise ApiError(response.status_code, response.text, parsed_body, response)

        raise ApiError(response.status_code, response.text, response=response)

    async def send_invoice(
        self,
        invoice_id: UUID,
        *,
        timeout: float | None = None,
    ) -> Invoice:
        path = "/invoices/{invoiceId}/send"
        path = path.replace("{invoiceId}", serialize_path("invoiceId", invoice_id))

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        response = await self._client.request(
            method="POST",
            url=f"{self._base_url}{path}",
            headers=headers,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            return Invoice.model_validate(response.json())
        if response.status_code == 409:
            parsed_body = ApiErrorModel.model_validate(response.json())
            raise ApiError(response.status_code, response.text, parsed_body, response)

        raise ApiError(response.status_code, response.text, response=response)
