# ============================================================================
# Generated by httpxgen. DO NOT EDIT.
# ============================================================================


from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from preview.shared.models import BaseEntity, Money


class InvoiceLineItem(BaseModel):
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    description: str
    quantity: int = Field(1, ge=1)
    amount: Money


class InvoiceStatus(StrEnum):
    DRAFT = "draft"
    SENT = "sent"
    PAID = "paid"
    VOID = "void"


class CreateInvoiceRequest(BaseModel):
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    customer_id: UUID
    line_items: list[InvoiceLineItem] = Field(min_length=1)
    status: InvoiceStatus = InvoiceStatus.DRAFT
    metadata: dict[str, str] = None


class Invoice(BaseEntity):
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    customer_id: UUID
    status: InvoiceStatus
    line_items: list[InvoiceLineItem]
    total: Money
    charge_id: str | None = None
    metadata: dict[str, str] = None


class InvoicePage(BaseModel):
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    items: list[Invoice]
    next_cursor: str | None


class ListInvoicesParams(BaseModel):
    status: InvoiceStatus | None = None
    cursor: str | None = None
    page_size: int = Field(25, ge=1, le=200)
