# ============================================================================
# Generated by httpxgen. DO NOT EDIT.
# ============================================================================


from enum import StrEnum


class HttpMethods(StrEnum):
    GET = "GET"
    PUT = "PUT"
    POST = "POST"
    DELETE = "DELETE"
    OPTIONS = "OPTIONS"
    HEAD = "HEAD"
    PATCH = "PATCH"
    TRACE = "TRACE"
