# ============================================================================
# Generated by httpxgen. DO NOT EDIT.
# ============================================================================


from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ApiErrorModel(BaseModel):
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    code: str
    message: str
    details: dict[str, Any] = None


class BaseEntity(BaseModel):
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str
    created_at: datetime


class Money(BaseModel):
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    amount_cents: int
    currency: str = Field(min_length=3, max_length=3)
