from enum import StrEnum
from functools import lru_cache

from jinja2 import DictLoader, Environment, StrictUndefined


class TemplateName(StrEnum):
    CLIENT = "client"
    ENUM = "enum"
    EXCEPTIONS = "exceptions"
    GENERATED_HEADER = "generated_header"
    HTTP_METHODS = "http_methods"
    MODEL = "model"
    MODELS = "models"
    OPERATION = "operation"
    PACKAGE_INIT = "package_init"
    SERIALIZATION = "serialization"
    SHARED_INIT = "shared_init"


def render_template(template_name: TemplateName, **context: object) -> str:
    return _environment().get_template(template_name.value).render(**context)


_GENERATED_HEADER_TEMPLATE = """\
# ============================================================================
# Generated by httpxgen. DO NOT EDIT.
# ============================================================================
"""

_EXCEPTIONS = '''\
class ApiError(Exception):
    """Raised for a documented error response or an unexpected status code."""

    def __init__(
        self,
        status_code: int,
        body: str,
        parsed_body: object | None = None,
        response: object | None = None,
    ) -> None:
        super().__init__(f"HTTP {status_code}: {body}")
        self.status_code = status_code
        self.body = body
        self.parsed_body = parsed_body
        self.response = response
'''

_HTTP_METHODS = """\
from enum import StrEnum


class HttpMethods(StrEnum):
    GET = "GET"
    PUT = "PUT"
    POST = "POST"
    DELETE = "DELETE"
    OPTIONS = "OPTIONS"
    HEAD = "HEAD"
    PATCH = "PATCH"
    TRACE = "TRACE"
"""

_SERIALIZATION = """\
from base64 import b64encode
from collections.abc import Mapping, Sequence
from enum import Enum
from typing import Any, NamedTuple
from urllib.parse import quote

Credential = str | tuple[str, str]

_RESERVED_CHARACTERS = ":/?#[]@!$&\'()*+,;="


class SecurityScheme(NamedTuple):
    kind: str
    location: str
    parameter_name: str
    prefix: str = ""


SECURITY_SCHEMES: dict[str, SecurityScheme] = {{ security_schemes }}


def scalar(value: Any) -> str:
    if isinstance(value, Enum):
        value = value.value
    if isinstance(value, bool):
        return "true" if value else "false"
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return str(value)


def serialize_simple(value: Any, *, explode: bool = False) -> str:
    value = _plain(value)
    if isinstance(value, Mapping):
        if explode:
            return ",".join(
                f"{scalar(key)}={scalar(item)}" for key, item in value.items()
            )
        return ",".join(scalar(item) for pair in value.items() for item in pair)
    if isinstance(value, (list, tuple)):
        return ",".join(scalar(item) for item in value)
    return scalar(value)


def serialize_query(
    name: str, value: Any, style: str = "form", *, explode: bool = True
) -> list[tuple[str, str]]:
    value = _plain(value)
    if style == "deepObject" and isinstance(value, Mapping):
        return [(f"{name}[{key}]", scalar(item)) for key, item in value.items()]
    if style == "form" and explode:
        if isinstance(value, Mapping):
            return [(scalar(key), scalar(item)) for key, item in value.items()]
        if isinstance(value, (list, tuple)):
            return [(name, scalar(item)) for item in value]
    delimiter = _DELIMITERS.get(style, ",")
    if isinstance(value, Mapping):
        pairs = [item for pair in value.items() for item in pair]
        return [(name, delimiter.join(scalar(item) for item in pairs))]
    if isinstance(value, (list, tuple)):
        return [(name, delimiter.join(scalar(item) for item in value))]
    return [(name, scalar(value))]


def serialize_path(
    name: str,
    value: Any,
    style: str = "simple",
    *,
    explode: bool = False,
    allow_reserved: bool = False,
) -> str:
    rendered = quote(
        serialize_simple(value, explode=explode),
        safe=_RESERVED_CHARACTERS if allow_reserved else "",
    )
    if style == "label":
        return f".{rendered}"
    if style == "matrix":
        return f";{name}={rendered}"
    return rendered


def apply_security(
    credentials: Mapping[str, Credential],
    requirements: Sequence[Sequence[str]],
    headers: dict[str, str],
    query: list[tuple[str, str]],
    cookies: dict[str, str],
) -> None:
    selected = next(
        (
            requirement
            for requirement in requirements
            if all(name in credentials for name in requirement)
        ),
        None,
    )
    if selected is None:
        choices = " or ".join(" + ".join(item) for item in requirements)
        raise ValueError(f"missing credentials for {choices}")
    for name in selected:
        scheme = SECURITY_SCHEMES[name]
        value = _credential_value(scheme, name, credentials[name])
        if scheme.location == "header":
            headers[scheme.parameter_name] = value
        elif scheme.location == "query":
            query.append((scheme.parameter_name, value))
        else:
            cookies[scheme.parameter_name] = value


_DELIMITERS = {"spaceDelimited": " ", "pipeDelimited": "|"}


def _plain(value: Any) -> Any:
    if hasattr(value, "model_dump"):
        return value.model_dump(mode="json", by_alias=True, exclude_none=True)
    return value


def _credential_value(scheme: SecurityScheme, name: str, credential: Credential) -> str:
    if scheme.kind == "basic":
        if not isinstance(credential, tuple):
            raise TypeError(f"credential {name!r} must be a (username, password) tuple")
        username, password = credential
        return f"Basic {b64encode(f'{username}:{password}'.encode()).decode()}"
    if not isinstance(credential, str):
        raise TypeError(f"credential {name!r} must be a string")
    return f"{scheme.prefix} {credential}" if scheme.prefix else credential
"""

_ENUM = """\
class {{ name }}(StrEnum):
{{ members }}
"""

_MODEL = """\
class {{ name }}({{ base }}):
    model_config = ConfigDict(extra="{{ extra_mode }}", populate_by_name=True)

{% for field in fields %}
    {{ field }}
{% endfor %}
{% if not fields %}
    pass
{% endif %}
"""

_MODELS = """\
from __future__ import annotations

{{ imports }}


{{ body }}
"""

_PACKAGE_INIT = """\
{{ imports }}

__all__ = [
{{ exports }}
]
"""

_CLIENT = """\
{{ imports }}


class {{ client_name }}:
    def __init__(
        self,
        client: httpx.AsyncClient,
        base_url: str,
        *,
        headers: Mapping[str, str] | None = None,
        credentials: Mapping[str, str | tuple[str, str]] | None = None,
        timeout: float = 30.0,
    ) -> None:
        self._client = client
        self._base_url = base_url.rstrip("/")
        self._headers = dict(headers) if headers else {}
        self._credentials = dict(credentials) if credentials else {}
        self._timeout = timeout

    async def aclose(self) -> None:
        await self._client.aclose()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.aclose()

{{ methods }}
"""

_OPERATION = """\
    async def {{ operation.name }}(
        self,
{{ signature }}        *,
{{ content_type_argument }}        timeout: float | None = None,
    ) -> {{ return_annotation }}:
{{ assignments }}
        response = await self._client.request(
            {{ request_arguments }},
        )

{{ response_handling }}
        raise ApiError(response.status_code, response.text, response=response)
"""


_SHARED_INIT = """\
from .exceptions import ApiError
from .http_methods import HttpMethods
from .serialization import (
    Credential,
    SecurityScheme,
    apply_security,
    scalar,
    serialize_path,
    serialize_query,
    serialize_simple,
)

__all__ = [
    "ApiError",
    "Credential",
    "HttpMethods",
    "SecurityScheme",
    "apply_security",
    "scalar",
    "serialize_path",
    "serialize_query",
    "serialize_simple",
]
"""

_TEMPLATES: dict[TemplateName, str] = {
    TemplateName.CLIENT: _CLIENT,
    TemplateName.ENUM: _ENUM,
    TemplateName.EXCEPTIONS: _EXCEPTIONS,
    TemplateName.GENERATED_HEADER: _GENERATED_HEADER_TEMPLATE,
    TemplateName.HTTP_METHODS: _HTTP_METHODS,
    TemplateName.MODEL: _MODEL,
    TemplateName.MODELS: _MODELS,
    TemplateName.OPERATION: _OPERATION,
    TemplateName.PACKAGE_INIT: _PACKAGE_INIT,
    TemplateName.SERIALIZATION: _SERIALIZATION,
    TemplateName.SHARED_INIT: _SHARED_INIT,
}


@lru_cache(maxsize=1)
def _environment() -> Environment:
    return Environment(
        loader=DictLoader({name.value: source for name, source in _TEMPLATES.items()}),
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )


GENERATED_HEADER = render_template(TemplateName.GENERATED_HEADER)
