"""All code-generation templates, kept as one module instead of many small files."""

from enum import StrEnum
from functools import lru_cache

from jinja2 import DictLoader, Environment, StrictUndefined


class TemplateName(StrEnum):
    CLIENT = "client"
    ENUM = "enum"
    EXCEPTIONS = "exceptions"
    GENERATED_HEADER = "generated_header"
    MODEL = "model"
    MODELS = "models"
    OPERATION = "operation"
    PACKAGE_INIT = "package_init"


_GENERATED_HEADER = """\
# ============================================================================
# Generated by httpxgen. DO NOT EDIT.
# ============================================================================
"""

_EXCEPTIONS = '''\
class ApiError(Exception):
    """Raised when a request completes with an unexpected status code."""

    def __init__(self, status_code: int, body: str) -> None:
        super().__init__(f"HTTP {status_code}: {body}")
        self.status_code = status_code
        self.body = body
'''

_ENUM = """\
class {{ name }}(StrEnum):
{{ members }}
"""

_MODEL = """\
class {{ name }}({{ base }}):
{% if forbid_extra %}
    model_config = ConfigDict(extra="forbid")

{% endif %}
{% for field in fields %}
    {{ field }}
{% endfor %}
{% if not fields %}
    pass
{% endif %}
"""

_MODELS = """\
{{ imports }}


{{ body }}
"""

_PACKAGE_INIT = """\
from .client import {{ client_name }}
from .exceptions import ApiError
{% if model_imports %}
from .models import ({{ model_imports }})
{% endif %}

__all__ = [
{{ exports }}
]
"""

_CLIENT = """\
{{ imports }}


class {{ client_name }}:
    def __init__(
        self,
        base_url: str,
        *,
        headers: Mapping[str, str] | None = None,
        timeout: float = 30.0,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        self._headers = dict(headers) if headers else {}
        self._timeout = timeout
        self._client = httpx.AsyncClient()

    async def aclose(self) -> None:
        await self._client.aclose()

    async def __aenter__(self) -> "{{ client_name }}":
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.aclose()

{{ methods }}
"""

_OPERATION = """\
    async def {{ operation.name }}(
        self,
{{ signature }}        *,
        timeout: float | None = None,
    ) -> {{ return_annotation }}:
{{ path_assignment }}{{ query_mapping }}{{ header_mapping }}
{% if has_body %}
        json_body = (
            TypeAdapter({{ operation.body_annotation }}).dump_python(
                body, mode="json", by_alias=True, exclude_none=True
            )
            if body is not None
            else None
        )

{% endif %}
        response = await self._client.request(
            {{ request_arguments }},
        )

{{ response_handling }}
        raise ApiError(response.status_code, response.text)
"""

_TEMPLATES: dict[TemplateName, str] = {
    TemplateName.CLIENT: _CLIENT,
    TemplateName.ENUM: _ENUM,
    TemplateName.EXCEPTIONS: _EXCEPTIONS,
    TemplateName.GENERATED_HEADER: _GENERATED_HEADER,
    TemplateName.MODEL: _MODEL,
    TemplateName.MODELS: _MODELS,
    TemplateName.OPERATION: _OPERATION,
    TemplateName.PACKAGE_INIT: _PACKAGE_INIT,
}


def render_template(template_name: TemplateName, **context: object) -> str:
    """Render one of the templates shipped in this module."""
    return _environment().get_template(template_name.value).render(**context)


@lru_cache(maxsize=1)
def _environment() -> Environment:
    return Environment(
        loader=DictLoader({name.value: source for name, source in _TEMPLATES.items()}),
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )


GENERATED_HEADER = render_template(TemplateName.GENERATED_HEADER)
