# ============================================================================
# Generated by httpxgen. DO NOT EDIT.
# ============================================================================


from collections.abc import Mapping
from typing import Any, Literal, Self
from uuid import UUID

import httpx
from pydantic import TypeAdapter

from preview.payments.models import (
    Charge,
    ChargeError,
    ChargeEvent,
    ChargePage,
    ChargeStatus,
    CreateChargeRequest,
    Customer,
    CustomerProfileRequest,
    CustomerProfileResponse,
    ImportCustomerProfileBody,
    ListChargesParams,
    PaymentMethod,
    PaymentMethodReference,
    UploadCustomerAvatarBody,
)
from preview.shared import (
    ApiError,
    HttpMethods,
    apply_security,
    serialize_path,
    serialize_query,
)
from preview.shared.models import ApiErrorModel


class PaymentsClient:
    def __init__(
        self,
        client: httpx.AsyncClient,
        base_url: str,
        *,
        headers: Mapping[str, str] | None = None,
        credentials: Mapping[str, str | tuple[str, str]] | None = None,
        timeout: float = 30.0,
    ) -> None:
        self._client = client
        self._base_url = base_url.rstrip("/")
        self._headers = dict(headers) if headers else {}
        self._credentials = dict(credentials) if credentials else {}
        self._timeout = timeout

    async def aclose(self) -> None:
        await self._client.aclose()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.aclose()

    async def list_charges(
        self,
        status: ChargeStatus | None = None,
        cursor: str | None = None,
        page_size: int = 25,
        *,
        timeout: float | None = None,
    ) -> ChargePage:
        path = "/charges"

        params = ListChargesParams(
            status=status,
            cursor=cursor,
            page_size=page_size,
        )
        query: list[tuple[str, str]] = []
        if params.status is not None:
            query.extend(serialize_query("status", params.status))
        if params.cursor is not None:
            query.extend(serialize_query("cursor", params.cursor))
        query.extend(serialize_query("page_size", params.page_size))

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, query, {})

        response = await self._client.request(
            method=HttpMethods.GET,
            url=f"{self._base_url}{path}",
            params=query,
            headers=headers,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            return ChargePage.model_validate(response.json())

        raise ApiError(response.status_code, response.text, response=response)

    async def create_charge(
        self,
        body: CreateChargeRequest,
        *,
        timeout: float | None = None,
    ) -> Charge:
        path = "/charges"

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        json_body = TypeAdapter(CreateChargeRequest).dump_python(
            body, mode="json", by_alias=True, exclude_none=True
        )

        response = await self._client.request(
            method=HttpMethods.POST,
            url=f"{self._base_url}{path}",
            headers=headers,
            json=json_body,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 201:
            return Charge.model_validate(response.json())
        if response.status_code == 402:
            parsed_body = ChargeError.model_validate(response.json())
            raise ApiError(response.status_code, response.text, parsed_body, response)

        raise ApiError(response.status_code, response.text, response=response)

    async def list_charge_events(
        self,
        charge_id: str,
        *,
        timeout: float | None = None,
    ) -> list[ChargeEvent]:
        path = "/charges/{chargeId}/events"
        path = path.replace("{chargeId}", serialize_path("chargeId", charge_id))

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        response = await self._client.request(
            method=HttpMethods.GET,
            url=f"{self._base_url}{path}",
            headers=headers,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            return TypeAdapter(list[ChargeEvent]).validate_python(response.json())

        raise ApiError(response.status_code, response.text, response=response)

    async def create_customer_profile(
        self,
        body: CustomerProfileRequest,
        *,
        timeout: float | None = None,
    ) -> CustomerProfileResponse:
        path = "/customer-profiles"

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        json_body = TypeAdapter(CustomerProfileRequest).dump_python(
            body, mode="json", by_alias=True, exclude_none=True
        )

        response = await self._client.request(
            method=HttpMethods.POST,
            url=f"{self._base_url}{path}",
            headers=headers,
            json=json_body,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 201:
            return CustomerProfileResponse.model_validate(response.json())

        raise ApiError(response.status_code, response.text, response=response)

    async def replace_customer_archive(
        self,
        body: bytes,
        *,
        timeout: float | None = None,
    ) -> None:
        path = "/customer-profiles/archive"

        headers = dict(self._headers)
        headers.setdefault("Content-Type", "application/octet-stream")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        response = await self._client.request(
            method=HttpMethods.PUT,
            url=f"{self._base_url}{path}",
            headers=headers,
            content=body,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 204:
            return None

        raise ApiError(response.status_code, response.text, response=response)

    async def upload_customer_avatar(
        self,
        body: UploadCustomerAvatarBody,
        *,
        timeout: float | None = None,
    ) -> None:
        path = "/customer-profiles/avatar"

        headers = dict(self._headers)

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        body_data = TypeAdapter(UploadCustomerAvatarBody).dump_python(
            body, mode="python", by_alias=True, exclude_none=True
        )
        form_data = dict(body_data)
        files: dict[str, bytes] = {}
        if "file" in form_data:
            files["file"] = form_data.pop("file")

        response = await self._client.request(
            method=HttpMethods.POST,
            url=f"{self._base_url}{path}",
            headers=headers,
            data=form_data,
            files=files,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 204:
            return None

        raise ApiError(response.status_code, response.text, response=response)

    async def convert_customer_profile(
        self,
        body: CustomerProfileRequest | str,
        *,
        content_type: Literal["application/json", "text/plain"] = "application/json",
        timeout: float | None = None,
    ) -> CustomerProfileResponse | str:
        path = "/customer-profiles/convert"

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json, text/plain")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        body_arguments: dict[str, Any] = {}
        if content_type == "application/json":
            body_arguments["json"] = TypeAdapter(CustomerProfileRequest).dump_python(
                body, mode="json", by_alias=True, exclude_none=True
            )
        elif content_type == "text/plain":
            body_arguments["content"] = body
            headers.setdefault("Content-Type", "text/plain")

        response = await self._client.request(
            method=HttpMethods.POST,
            url=f"{self._base_url}{path}",
            headers=headers,
            **body_arguments,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            response_content_type = response.headers.get("Content-Type", "")
            response_content_type = response_content_type.split(";", 1)[0].lower()
            if response_content_type == "application/json":
                parsed_body = CustomerProfileResponse.model_validate(response.json())
            elif response_content_type == "text/plain":
                parsed_body = response.text
            else:
                raise ApiError(
                    response.status_code,
                    f"unsupported response Content-Type: {response_content_type}",
                    response=response,
                )
            return parsed_body

        raise ApiError(response.status_code, response.text, response=response)

    async def import_customer_profile(
        self,
        body: ImportCustomerProfileBody,
        *,
        timeout: float | None = None,
    ) -> None:
        path = "/customer-profiles/import"

        headers = dict(self._headers)

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        form_data = TypeAdapter(ImportCustomerProfileBody).dump_python(
            body, mode="python", by_alias=True, exclude_none=True
        )

        response = await self._client.request(
            method=HttpMethods.POST,
            url=f"{self._base_url}{path}",
            headers=headers,
            data=form_data,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 204:
            return None

        raise ApiError(response.status_code, response.text, response=response)

    async def get_customer(
        self,
        customer_id: UUID,
        *,
        timeout: float | None = None,
    ) -> Customer:
        path = "/customers/{customerId}"
        path = path.replace("{customerId}", serialize_path("customerId", customer_id))

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        response = await self._client.request(
            method=HttpMethods.GET,
            url=f"{self._base_url}{path}",
            headers=headers,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            return Customer.model_validate(response.json())
        if response.status_code == 404:
            parsed_body = ApiErrorModel.model_validate(response.json())
            raise ApiError(response.status_code, response.text, parsed_body, response)

        raise ApiError(response.status_code, response.text, response=response)

    async def create_payment_method(
        self,
        body: PaymentMethod,
        *,
        timeout: float | None = None,
    ) -> PaymentMethod:
        path = "/payment-methods"

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        json_body = TypeAdapter(PaymentMethod).dump_python(
            body, mode="json", by_alias=True, exclude_none=True
        )

        response = await self._client.request(
            method=HttpMethods.POST,
            url=f"{self._base_url}{path}",
            headers=headers,
            json=json_body,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 201:
            return TypeAdapter(PaymentMethod).validate_python(response.json())

        raise ApiError(response.status_code, response.text, response=response)

    async def lookup_payment_method(
        self,
        body: PaymentMethodReference,
        *,
        timeout: float | None = None,
    ) -> PaymentMethod:
        path = "/payment-methods/lookup"

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        json_body = TypeAdapter(PaymentMethodReference).dump_python(
            body, mode="json", by_alias=True, exclude_none=True
        )

        response = await self._client.request(
            method=HttpMethods.POST,
            url=f"{self._base_url}{path}",
            headers=headers,
            json=json_body,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            return TypeAdapter(PaymentMethod).validate_python(response.json())

        raise ApiError(response.status_code, response.text, response=response)
