# ============================================================================
# Generated by httpxgen. DO NOT EDIT.
# ============================================================================


from collections.abc import Mapping
from typing import Self
from uuid import UUID

import httpx
from pydantic import TypeAdapter

from preview.payments.models import (
    Charge,
    ChargeError,
    ChargeEvent,
    ChargePage,
    ChargeStatus,
    CreateChargeRequest,
    Customer,
    ListChargesParams,
    PaymentMethod,
    PaymentMethodReference,
)
from preview.shared import ApiError, apply_security, serialize_path, serialize_query
from preview.shared.models import ApiErrorModel


class PaymentsClient:
    def __init__(
        self,
        client: httpx.AsyncClient,
        base_url: str,
        *,
        headers: Mapping[str, str] | None = None,
        credentials: Mapping[str, str | tuple[str, str]] | None = None,
        timeout: float = 30.0,
    ) -> None:
        self._client = client
        self._base_url = base_url.rstrip("/")
        self._headers = dict(headers) if headers else {}
        self._credentials = dict(credentials) if credentials else {}
        self._timeout = timeout

    async def aclose(self) -> None:
        await self._client.aclose()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.aclose()

    async def list_charges(
        self,
        status: ChargeStatus | None = None,
        cursor: str | None = None,
        page_size: int = 25,
        *,
        timeout: float | None = None,
    ) -> ChargePage:
        path = "/charges"

        params = ListChargesParams(
            status=status,
            cursor=cursor,
            page_size=page_size,
        )
        query: list[tuple[str, str]] = []
        if params.status is not None:
            query.extend(serialize_query("status", params.status))
        if params.cursor is not None:
            query.extend(serialize_query("cursor", params.cursor))
        query.extend(serialize_query("page_size", params.page_size))

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, query, {})

        response = await self._client.request(
            method="GET",
            url=f"{self._base_url}{path}",
            params=query,
            headers=headers,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            return ChargePage.model_validate(response.json())

        raise ApiError(response.status_code, response.text, response=response)

    async def create_charge(
        self,
        body: CreateChargeRequest,
        *,
        timeout: float | None = None,
    ) -> Charge:
        path = "/charges"

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        json_body = TypeAdapter(CreateChargeRequest).dump_python(
            body, mode="json", by_alias=True, exclude_none=True
        )

        response = await self._client.request(
            method="POST",
            url=f"{self._base_url}{path}",
            headers=headers,
            json=json_body,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 201:
            return Charge.model_validate(response.json())
        if response.status_code == 402:
            parsed_body = ChargeError.model_validate(response.json())
            raise ApiError(response.status_code, response.text, parsed_body, response)

        raise ApiError(response.status_code, response.text, response=response)

    async def list_charge_events(
        self,
        charge_id: str,
        *,
        timeout: float | None = None,
    ) -> list[ChargeEvent]:
        path = "/charges/{chargeId}/events"
        path = path.replace("{chargeId}", serialize_path("chargeId", charge_id))

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        response = await self._client.request(
            method="GET",
            url=f"{self._base_url}{path}",
            headers=headers,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            return TypeAdapter(list[ChargeEvent]).validate_python(response.json())

        raise ApiError(response.status_code, response.text, response=response)

    async def get_customer(
        self,
        customer_id: UUID,
        *,
        timeout: float | None = None,
    ) -> Customer:
        path = "/customers/{customerId}"
        path = path.replace("{customerId}", serialize_path("customerId", customer_id))

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        response = await self._client.request(
            method="GET",
            url=f"{self._base_url}{path}",
            headers=headers,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            return Customer.model_validate(response.json())
        if response.status_code == 404:
            parsed_body = ApiErrorModel.model_validate(response.json())
            raise ApiError(response.status_code, response.text, parsed_body, response)

        raise ApiError(response.status_code, response.text, response=response)

    async def create_payment_method(
        self,
        body: PaymentMethod,
        *,
        timeout: float | None = None,
    ) -> PaymentMethod:
        path = "/payment-methods"

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        json_body = TypeAdapter(PaymentMethod).dump_python(
            body, mode="json", by_alias=True, exclude_none=True
        )

        response = await self._client.request(
            method="POST",
            url=f"{self._base_url}{path}",
            headers=headers,
            json=json_body,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 201:
            return TypeAdapter(PaymentMethod).validate_python(response.json())

        raise ApiError(response.status_code, response.text, response=response)

    async def lookup_payment_method(
        self,
        body: PaymentMethodReference,
        *,
        timeout: float | None = None,
    ) -> PaymentMethod:
        path = "/payment-methods/lookup"

        headers = dict(self._headers)
        headers.setdefault("Accept", "application/json")

        apply_security(self._credentials, [("bearerAuth",)], headers, [], {})

        json_body = TypeAdapter(PaymentMethodReference).dump_python(
            body, mode="json", by_alias=True, exclude_none=True
        )

        response = await self._client.request(
            method="POST",
            url=f"{self._base_url}{path}",
            headers=headers,
            json=json_body,
            timeout=self._timeout if timeout is None else timeout,
        )

        if response.status_code == 200:
            return TypeAdapter(PaymentMethod).validate_python(response.json())

        raise ApiError(response.status_code, response.text, response=response)
