# ============================================================================
# Generated by httpxgen. DO NOT EDIT.
# ============================================================================


class ApiError(Exception):
    """Raised when a request completes with an unexpected status code."""

    def __init__(self, status_code: int, body: str) -> None:
        super().__init__(f"HTTP {status_code}: {body}")
        self.status_code = status_code
        self.body = body
