# ============================================================================
# Generated by httpxgen. DO NOT EDIT.
# ============================================================================


class ApiError(Exception):
    """Raised for a documented error response or an unexpected status code."""

    def __init__(
        self,
        status_code: int,
        body: str,
        parsed_body: object | None = None,
        response: object | None = None,
    ) -> None:
        super().__init__(f"HTTP {status_code}: {body}")
        self.status_code = status_code
        self.body = body
        self.parsed_body = parsed_body
        self.response = response
