# ============================================================================
# Generated by httpxgen. DO NOT EDIT.
# ============================================================================


from datetime import datetime
from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import BaseModel, Field


class PaymentMethodType(StrEnum):
    CARD = "card"
    BANK_TRANSFER = "bank_transfer"


class ChargeEventType(StrEnum):
    CHARGE_CREATED = "charge.created"
    CHARGE_REFUNDED = "charge.refunded"


class Address(BaseModel):
    street: str
    city: str
    postal_code: str | None = None
    country: str = Field(min_length=2, max_length=2)


class BankTransferPaymentMethod(BaseModel):
    type: Literal[PaymentMethodType.BANK_TRANSFER]
    iban: str
    account_holder: str


class BaseEntity(BaseModel):
    id: str
    created_at: datetime


class CardPaymentMethod(BaseModel):
    type: Literal[PaymentMethodType.CARD]
    card_number: str
    exp_month: int = Field(ge=1, le=12)
    exp_year: int
    billing_address: Address | None = None


class ChargeStatus(StrEnum):
    PENDING = "pending"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    REFUNDED = "refunded"


class Money(BaseModel):
    amount_cents: int
    currency: str = Field(min_length=3, max_length=3)


PaymentMethod = Annotated[
    CardPaymentMethod | BankTransferPaymentMethod,
    Field(discriminator="type"),
]


class Charge(BaseEntity):
    amount: Money
    status: ChargeStatus
    payment_method: PaymentMethod
    refunded_amount: Money = None
    metadata: dict[str, str] | None = None


class ChargeCreatedEvent(BaseModel):
    type: Literal[ChargeEventType.CHARGE_CREATED]
    occurred_at: datetime
    charge: Charge


class ChargeError(BaseModel):
    code: Literal["card_declined", "insufficient_funds", "invalid_iban"]
    message: str
    charge: Charge | None = None


class ChargeRefundedEvent(BaseModel):
    type: Literal[ChargeEventType.CHARGE_REFUNDED]
    occurred_at: datetime
    amount: Money
    reason: Literal["duplicate", "fraudulent", "requested_by_customer"] = None


ChargeEvent = Annotated[
    ChargeCreatedEvent | ChargeRefundedEvent,
    Field(discriminator="type"),
]


class ChargePage(BaseModel):
    items: list[Charge]
    next_cursor: str | None


class CreateChargeRequest(BaseModel):
    amount: Money
    payment_method: PaymentMethod
    customer_id: UUID | None = None
    metadata: dict[str, str] | None = None
    idempotency_key: UUID | None = None


class Customer(BaseEntity):
    email: str
    billing_profile: dict[str, Any]
    metadata: dict[str, str] | None = None


class PaymentApiError(BaseModel):
    code: str
    message: str
    details: dict[str, Any] | None = None


class ListChargesParams(BaseModel):
    status: ChargeStatus | None = None
    cursor: str | None = None
    page_size: int | None = None
